### ISSUE TITLE
Spec QA: Callout flow

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee#100]
![image](https://user-images.githubusercontent.com/159868/148097956-171633b1-f3dc-448d-aa8c-e0d18754f1b6.png)
(this preview is only the first page of the whole flow)

* [Original Trello card](https://trello.com/c/hQMwyZUw/175-design-separated-steps-of-setting-up-a-call-out)
* [Penpot spec](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4a449480-5910-11ec-8ccc-4b86b12c67d6&index=0&share-id=778def60-5cfb-11ec-826f-e949c75b760d)

**Comment by rlafuente** [comment]
[copypasting Julia's review from Trello]

@aiscarvalho @rlafuente This looks great! Just from the user perspective from me (I now realise it is only in QA not review but I leave it here anyway:

- Step 1 and following:
- Can we have info buttons instead of all content open to the right side? Can we also include links to further information within those descriptions?
- "Save draft" button I wouldn't know what exactly to expect. Does that save and take me away from the page? At the same time we have the info at the bottom: Last saved 1 minute ago. Shouldn't those be connected? "Save now" vs. "Save draft" And the "Last saved 2 minute ago" moves underneath that button.
- Step 2:
- "Hide this callout" > should we write more precisely "Hide this callout from user dashboard" ?
- Question for requirements: Can we have people leave their contact data when/after filling in a survey just to be contacted but that data is not connected with the exact survey answers?
- Page 8/Step 6:
- I do find it a little confusing that this comes in a new screen. Wouldn't it be easier to include in the screen before?
- There should be no need here if it stays a separate page to remove the tags I think.
- And regarding the copy-functionality. I think what I maybe rather need is a hint: You can always check all the merge tags you created here. Because I probably don't need to use the merge tag right away but later on. I need to know where to go then to find it. If, as an admin I have one overview page for a call-out it is probably also good to see the tags there right away (and copy) or if I get from the call-outs overview page to the call-out summary page and there I can copy
- Page 9, Final Screen: The Callout summary is something we maybe still need to chat through? Is it a page that I can always get back to from the call-outs overview page. We could think about it like that and make it look the same here in the process and there. It then should have an edit button at the bottom or for single elements that take me right to that step? Should it also have the preview button again?

**Comment by rlafuente** [comment]
#### Info texts for step 1 and following
We decided to try a different layout the info texts since there will probably be many, contain more text than usual and will include links.

This is an info text from other part of beabee for reference:

![image](https://user-images.githubusercontent.com/159868/148098423-ade16294-5c86-4f63-b9a3-9dbc603691e3.png)

...though we imagine you have something else in mind because these aren’t buttons.

We are not 100% sure about using infobuttons here, both because of visual repetition, like:

![image](https://user-images.githubusercontent.com/159868/148098593-7aa1b725-acae-4c10-aef9-ed733db1e8d3.png)

...and the fact that they're not very practical for larger amounts of text; also, we can't use links with them.

![image](https://user-images.githubusercontent.com/159868/148098628-43ee1409-35f4-4603-9799-dd82b359c949.png)

#### Other points

**Save Draft**: Thanks for picking this up. The button layout (back / next step – save draft) was something we were still figuring out and after reading your commment it becomes clearer.

"Save draft" would just save the callout at any point but not take the user out of the screen he’s in. We agree that “Last saved x minutes” should be together with “Save draft” and would propose to reorder the buttons:

![image](https://user-images.githubusercontent.com/159868/148098743-a76615e6-d088-44cd-bec9-e65e66c6948d.png)

**Hide this callout**: yes, a clearer copy is needed. Since hiding goes beyond the dashboard, how about the more generic “Hide this callout from users”?

**Merge tags (page 8, step 6)**: this step was listed in the mural board as a summary of the merge tags created in the previous step (5).
We agree that we could just have step 5 and include the “merge tag reference” in that step and the final callout summary (it’s useful to have the references).

**Share and embed URLs (page 9, step 7)**: We think the share and embed URLs should only appear in the final summary of the callout, once it has been published. In retrospect, it seems out of place to have these links if the callout is still a draft. For reference, here's a screenshot of the current design:

![image](https://user-images.githubusercontent.com/159868/148099098-3abe2dc4-3ac8-4d8f-99f6-d8ba58aa01c0.png)

**Comment by wpf500** [comment]
Looks great generally, can't wait to see a usable create callout flow live!

A few comments:
* I really like the help text being on the right so would vote against help icons
* If the help text above stays, could you do a mobile design for one of the screens to show how the text will appear on mobile
* The user won't need to edit raw HTML (e.g. in the intro text). I recently added [Quill](https://quilljs.com/) to the legacy app and intend to do in the frontend too. I assume this will make you happy but just thought I'd mention for clarity
* Agreed we could remove the Mailchimp summary step
* Agreed the links don't really make sense pre publish

Looking at this (and I think you've alluded to it above), I think there should be a pre-publishing summary that shows a few key details (e.g. when it will start/finish etc.) then the button on that page says "Publish" or "Schedule" depending on whether start date is in the future or not, then the "All done!" page has the the URLs appear on it. Maybe we should chat about this in the next backlog gardening session?

**Comment by aiscarvalho** [comment]
![image](https://user-images.githubusercontent.com/122730/148991464-d92eef28-a56c-40f6-a7de-fa14eb19be21.png)

We reviewed the last step of the creation flow, just before publishing/scheduling the callout. We included a summary of the most important details and the mailchimp merge tags.

And we agree it would be great to chat about the "All done!" page in the next backlog session.

**Comment by aiscarvalho** [comment]
Here's a screen in mobile, to show how the help texts would be laidout. ([see it penpot](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=3d4a0500-7303-11ec-a0a1-939282881e52&index=0&share-id=d2570be0-73ce-11ec-8da6-c2b142838c8b))

While putting this screen together we had some doubts regarding the layout for the bottom buttons -- Save draft / Back / Continue -- since they're hard to fit all in the same row.
We were wondering if "Save draft" makes sense to have as an action or if we can replace it by an autosave and a subtle "✔Saved" message.

![image](https://user-images.githubusercontent.com/122730/149191549-6cdca55b-0c1b-460c-8444-3643838058d7.png)

**Comment by julia-hildebrand** [comment]
The improvements look really good to me 

- I think for "save draft" it makes sense now. On mobile, it is not really too much. I think there will be very little use of this on mobile. Except for the quick on-the-go-change because people spot a mistake late or something. Let's do what is quicker.
- I agree with Will that the explainers should stay to the right. Maybe that was a misunderstanding from one of my comments. I just thought on some things we will have even deeper information and want to link to other pages within those explainers. That is actually incorporated on some pages in penpot. 
- "Hide this call-out from user dashboard" makes most sense to me. (In penpot it is still Hide this callout)
- 
**Summary page**

- The summary page looks great to me. I think it can be the page now that also is linked to in the overview list of all call-outs. From that perspective I think it might need:  
1) An indicator what the status of this call-out is. (Draft, Scheduled, Expired, Archived ...?), if we have that and there is are also the dates, we don't need the "Schedule to start in two weeks."
2) Then we can switch to neutral language "start date" "end date" so it works no matter if the call-out has ended or not started yet. 
3) The button Back could say "Edit" instead. 
4) Do you actually make changes on this page now or is it just the summary? When can probably lose the save button

> I see now in Penpot page 10 you have another design. Can't we merge the two?

**Success page**
Also great! 
1) just looking like a one-way street now. wonder where we want people to go next. Not a big deal though as they hopefully use the links etc. 
2) Preview: the headline "Your Callout" can actually say "Preview"

**Comment by rlafuente** [comment]
Yep, this was reviewed later on and I think it's wrapped, closing!
