### ISSUE TITLE
Proposal: Callout state and UI review 

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee#111]
The current set of states and options has a few issues:
- It is confusing to have a draft with a scheduled publish date, and it makes sense to distinguish between actual drafts and callouts that are not yet live but are scheduled to.
  - Proposal: **Scheduled** posts are its own state, and **drafts** don't have a start date set yet (when it is set, they become open or scheduled). Draft should mean unfinished, not scheduled.
- At the moment there are 2 possible states for callouts past their finish: **Expired** and **Closed**, both of which are not 100% clear in what they mean (expired implies that it's stale, and closed implies a specific action to close it)
  - Proposal: Use a single **Ended** state for callouts that are past their end date or have been manually closed. 
- The UI for deciding on how/when to publish is not clear on the implications of each choice
  - Proposal: Move the start/end date choices to the end of the creation process, with the option to not set them and keep the callout as a draft. Here's a quick mockup:

![](https://i.imgur.com/zgtY5EI.png)

Possible choices:
- If a start date is set to now, the callout is published and has the **Open** state
- If the start date is set to a future date, the callout is only published then, having the **Scheduled** state until that date
- If no start date is set, it is kept as a **Draft**

Other notes on this UI:
- The "Schedule" button should change to "Publish" if the start date is set to "Now"
- The option to keep it as a draft makes it unnecessary to add a "No start date" option
- We thought that the end date option of "Until manually closed" sounds less definite than "Open forever"

To wrap up, this would be the new set of possible states for the callouts:
- Draft
- Scheduled
- Open
- Ended

We're not 100% sure about some of these details so would love to know your thoughts!

**Comment by lb1253** [comment]
> **Proposal: Scheduled posts are its own state, and drafts don't have a start date set yet**

I agree with this proposal. This is like in Mailchimp.

> **Proposal: Use a single Ended state for callouts that are past their end date or have been manually closed.**

Agree, makes sense to combine expired and closed - no clear value in differentiating

> **Proposal: Move the start/end date choices to the end of the creation process, with the option to not set them and keep the callout as a draft.**

Looks good and I agree with your suggestions.
A time on the callout start is needed. But also need clarity on visibility of the call-out to users. Scheduling + closing are visibility and access controls. 

The main reason for scheduling is to avoid users seeing the callout before it is ready to launch, and end date avoid users seeing it + stop them responding when it should be closed. Unlike publishing newsletters or articles, call outs are active listening (collecting information rather than publishing information), so it's important that, if call outs are being seen by users, they are not open when they should be closed (ie dont say you're listening when you're not).

Scheduling and visibility toggles are one way to prompt admins to stay on top of that, but there are also other ways (e.g. email or dashboard reminders). Admins may not know exactly when they want a call out to close, and there are different use cases for shorter high volume call outs vs longer term open ended, low volume call outs. It might feel difficult for an admin to set an arbitrary end date.. Some further understanding of admin needs or expectations on stand and end dates might be useful for adjusting the UI or at least copy or prompts, but this is good enough for now - maybe with some clarity on what publishing means in terms of visibility. 

The main questions I see on scheduling are:
1. What does publishing now mean in terms of the visibility of the callout for them?
2. Why might they want to schedule rather than publish now?
3. Why might they want to close the call out on a specific date?
4. How often do they have a desired start or end date for a call out?

In my experience:
1. Appears on the call-outs page and link can be shared for users to access the call out. Immediately, there's a small chance a logged in member may see it, but admin actions are needed for real visibility (newsletter CTA linking to the call out, post on website). We have a visibility toggle for whether call-outs appear on the call-outs page visible to users.
2. Don't want to publish now (call out is ready, but not the right time to launch)
3. Don't want responses after that date. Don't want users seeing + responding to old call outs where we won't use their responses.
4. It varies. It's good to prompt a deadline for using/analysing responses. But it's not always obvious how long we want to have a call-out open, so either put a close date some further time in the future or no end date. Usually prefer to immediately publish to avoid risk of sending users a link to respond to a closed call out, and schedule time depends a lot on newsletter scheduling time, which can be flexible.

**Comment by wpf500** [comment]
Yeah I like these proposed changes, much more intuitive :+1:.

**Comment by rlafuente** [comment]
Wow, thank you so much for such an extensive and insightful review!

> good enough for now - maybe with some clarity on what publishing means in terms of visibility.

"good enough" is indeed a good aim for now :-) I think we can try some finetuning for the MVP, but figure out how it works with users before trying out larger changes.

One detail that we did not address is the "Hidden" status, which right now is a parallel kind of state, and that's not great. We'll think this up and update here, because we shouldn't have a set of callout states + an extra possible state that is set elsewhere.

**Comment by wpf500** [comment]
I think the hidden setting should be separate from the callout state. A hidden callout can have all the same states as a visible one (draft, scheduled, live, ended), but it just doesn't appear on the callouts page. It's basically for callouts you only want people to see who have the link, so maybe it could be better expressed as visibility or share settings (a la Google Drive):
* Public: callout is visible on the callouts list
* Hidden: only those with the link can see the callout

This might also be where in the future the ability to only do a callout to a segment of users fits nicely, e.g. public to all, public to subset, hidden

**Comment by julia-hildebrand** [comment]
@rlafuente This is looking really good to me too!

**Comment by rlafuente** [comment]
Yes, let's!
